app/phostel/routes.py
from flask import Flask, request, render_template, redirect, url_for, render_template_string, send_from_directory, abort, Blueprint, current_app, abort
import os
from PIL import Image as PILImage, ExifTags
import mimetypes
from flask_login import login_required, current_user
import sqlite3
from werkzeug.utils import secure_filename
import uuid
from sqlalchemy import Column, String, ForeignKey, or_, and_
from sqlalchemy.orm import relationship, joinedload
import uuid
from app import db
import time
from datetime import datetime
from app.auth.routes import User
import humanize

# konfigurasi
phostel = Blueprint('phostel', __name__)

class Image(db.Model):
    __tablename__ = 'image'
    id = db.Column(db.String(36), primary_key=True)  # UUID
    filename = db.Column(db.String(120), nullable=False)
    title = db.Column(db.String(120))
    filepath = db.Column(db.String(120), nullable=False)
    tag = db.Column(db.String)
    like = db.Column(db.Integer, default=0)
    upload_date = db.Column(db.Integer, default=lambda: int(time.time()))
    height = db.Column(db.Integer)
    width = db.Column(db.Integer)

    # Foreign key referencing the User model
    user_id = Column(db.String(36), ForeignKey('user.id'), nullable=False)

    # Relationship to User model
    user = relationship('User', back_populates='images')

    __table_args__ = (db.UniqueConstraint('user_id', 'id', name='_user_image_uc'),)

class Like(db.Model):
    __tablename__ = 'like'
    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.String(36), db.ForeignKey('user.id'), nullable=False)
    image_id = db.Column(db.String(36), db.ForeignKey('image.id'), nullable=False)

    __table_args__ = (
        db.UniqueConstraint('user_id', 'image_id', name='_user_image_uc'),
    )

def dimen(filename):
    image_path = os.path.join('static', 'uploads', filename)
    with PILImage.open(image_path) as img:
        return img.width, img.height
    
@phostel.route('/secret')
def secret():
    return "secret!"

@phostel.route('/')
def index():
    page = 1
    per_page = 6

    images_paginated = (
        Image.query
        .options(joinedload(Image.user))
        .order_by(Image.upload_date.desc())
        .paginate(page=page, per_page=per_page)
    )

    images = images_paginated.items

    image_data = []
    for image in images:
        like_count = Like.query.filter_by(image_id=image.id).count()
        liked = False
        if current_user.is_authenticated:
            liked = Like.query.filter_by(user_id=current_user.id, image_id=image.id).first() is not None

        image_data.append({
            'image': image,
            'like_count': like_count,
            'liked': liked
        })


    auth = current_user.is_authenticated
    
    return render_template('index.html', images=image_data, page=page, has_next=images_paginated.has_next, auth=auth, current_user=current_user)

@phostel.route('/load')
def load():
    page = request.args.get('page', 1, type=int)
    per_page = 6

    images_paginated = (
        Image.query
        .options(joinedload(Image.user))
        .order_by(Image.upload_date.desc())
        .paginate(page=page, per_page=per_page)
    )

    images = images_paginated.items

    image_data = []
    for image in images:
        like_count = Like.query.filter_by(image_id=image.id).count()
        liked = False
        if current_user.is_authenticated:
            liked = Like.query.filter_by(user_id=current_user.id, image_id=image.id).first() is not None

        image_data.append({
            'image': image,
            'like_count': like_count,
            'liked': liked
        })

    return render_template('_load.html', images=image_data, page=page, has_next=images_paginated.has_next)

@phostel.route('/load_related')
def load_related():
    page = request.args.get('page', 1, type=int)
    user_id = request.args.get('user_id')
    exclude_id = request.args.get('exclude_id')

    query = Image.query.filter(Image.user_id == user_id)
    if exclude_id:
        query = query.filter(Image.id != exclude_id)

    per_page = 6

    images = query.options(joinedload(Image.user)) \
                  .order_by(Image.upload_date.desc()) \
                  .paginate(page=page, per_page=per_page)
    
    return render_template('_load_related.html', images=images.items, page=page, has_next=images.has_next, user_id=user_id, exclude_id=exclude_id)

@phostel.route('/load_user')
def load_user():
    page = request.args.get('page', 1, type=int)
    user_id = request.args.get('user_id')

    if not user_id:
        return "Missing user_id", 400

    query = Image.query.filter(Image.user_id == user_id)

    per_page = 6

    images = query.order_by(Image.upload_date.desc()).paginate(page=page, per_page=per_page)
    
    return render_template('_load_related.html', images=images.items, page=page, has_next=images.has_next, user_id=user_id)


@phostel.route('/upload')
@login_required
def upload():
    auth = current_user.is_authenticated
    return render_template('upload.html', auth=auth, current_user=current_user)

@phostel.route('/phostel/<uuid:item_id>')
def images(item_id):
    image = Image.query.get(str(item_id))
    user = image.user

    image_path = os.path.join(os.getcwd(), 'static', 'uploads', image.filename)

    try:
        with PILImage.open(image_path) as img:
            width, height = img.size
    except Exception as e:
        return f"Error opening image: {e}", 500

    if not image:
        abort(404)
    
    auth = current_user.is_authenticated
    
    page = 1
    per_page = 6
    images = Image.query.filter(Image.user_id == image.user_id, Image.id != image.id).options(joinedload(Image.user)).order_by(Image.upload_date.desc()).paginate(page=page, per_page=per_page)

    humanize.i18n.activate("id_ID")
    humanized_time = humanize.naturaltime(datetime.fromtimestamp(image.upload_date))
    liked = False
    if current_user.is_authenticated:
        liked = Like.query.filter_by(user_id=current_user.id, image_id=image.id).first() is not None

    like_count = Like.query.filter_by(image_id=image.id).count()

    return render_template('gambar.html', image=image, page=page, has_next=images.has_next, humanized_time=humanized_time, images=images.items, auth=auth, user=user, current_user=current_user, tags=image.tag, liked=liked, like_count=like_count, dimen={'width': width, 'height': height})

@phostel.route('/u/<user_id>')
def user(user_id):
    user = User.query.get(user_id)
    if not user:
        return render_template('404.html'), 404
    
    auth = current_user.is_authenticated

    humanize.i18n.activate("id_ID")
    humanized_time = humanize.naturaltime(datetime.fromtimestamp(user.birth))

    query = Image.query.filter(Image.user_id == user_id)

    page = request.args.get('page', 1, type=int)
    per_page = 6

    images = query.order_by(Image.upload_date.desc()).paginate(page=page, per_page=per_page)
    upload_count = Image.query.filter_by(user_id=user.id).count()

    owner = current_user.is_authenticated and current_user.id == user_id

    return render_template('user.html', user=user, images=images, owner=owner, upload_count=upload_count, auth=auth, has_next=images.has_next, page=page, humanized_time=humanized_time)

@phostel.route('/s')
def search():
    query = request.args.get('q', '').strip()
    filters = []

    user = User.query.all()

    auth = current_user.is_authenticated

    if not query:
        return redirect(url_for('phostel.index'))  # or just render the search form again
    else:
        keywords = query.split()

        # Search using full phrase first
        phrase_filter = or_(
            Image.title.ilike(f'%{query}%'),
            Image.tag.ilike(f'%{query}%')
        )

        # Then build individual word filters
        word_filters = [
            or_(
                Image.title.ilike(f'%{word}%'),
                Image.tag.ilike(f'%{word}%')
            ) for word in keywords
        ]

        results = Image.query.filter(or_(phrase_filter, *word_filters)).distinct().all()

        if not results:
            return render_template('404.html', query=query, auth=auth, current_user=current_user, user=user), 404  # Return a 404 page manually

        return render_template('search.html', images=results, query=query, current_user=current_user, auth=auth)

@phostel.route('/u/s/profile', methods=['GET', 'POST'])
@login_required
def user_profile():
    file = request.files.get('profile_picture')
    if not file or file.filename == '':
        return "No file selected", 400

    filename = secure_filename(file.filename)
    unique_name = f"{uuid.uuid4()}_{filename}"

    # Manually specify the absolute path to the static folder
    upload_dir = os.path.join(os.getcwd(), 'static', 'u_profiles')  # Using os.getcwd() to get the project root
    os.makedirs(upload_dir, exist_ok=True)  # Ensure the folder exists

    # Save file using the absolute path

    try:
        # Open the image using Pillow (without saving to disk first)
        img = PILImage.open(file)
        img.verify()  # Verify the image without loading it into memory
        file.seek(0)

        # Re-open the image because 'verify()' doesn't load it into memory
        img = PILImage.open(file)
        img = apply_exif_orientation(img)
        img = img.convert("RGB")
    except (IOError, SyntaxError) as e:
        return "File is not a valid image", 400

    save_path = os.path.join(upload_dir, unique_name)
    print("Saving to:", save_path)  # Debugging step to check where it saves

    max_size = (256, 256)  # Max width and height
    img.thumbnail(max_size)
    img.save(save_path, format="JPEG", quality=45, optimize=True)

    # Store the relative path in DB
    current_user.picture = f"u_profiles/{unique_name}"
    db.session.commit()

    return redirect(url_for('phostel.user', user_id=current_user.id))

def apply_exif_orientation(image):
    try:
        for orientation in ExifTags.TAGS.keys():

templates/_load.html
{% for data in images %}
    <div class="box max-w-full overflow-hidden">
            <a class="md:hidden pt-2 mb-2 flex px-2 items-center">
                <div>
                    {% if data.image.user.picture %}
                    <img src="{{ url_for('static', filename=data.image.user.picture) }}" alt="Profile Picture" class="mr-2 w-10 h-10 object-cover rounded-full active:brightness-70 hover:brightness-70">
                    {% else %}
                    <div class="mr-2 w-10 h-10 object-cover rounded-full bg-neutral-400 text-neutral-100 flex items-center justify-center select-none">
                        {{ data.image.user.username[0:1]|upper }}
                    </div>
                    {% endif %}
                </div>
                <div>
                    <p class="text-sm text-hitam-pastel truncate">{{ data.image.user.username }}</p>
                </div>
            </a>
            <a href="{{ url_for('phostel.images', item_id=data.image.id) }}">
                <div class="md:rounded-md overflow-hidden">
                    <img
                        src="{{ url_for('static', filename='uploads/lqip/' + data.image.filename) }}"
                        class="gallery bg-neutral-400 hover:brightness-70"
                        data-src="{{ url_for('static', filename='uploads/thumbnails/' + data.image.filename) }}"
                        loading="eager"
                        style="aspect-ratio: {{ data.image.width }} / {{ data.image.height }};"
                    >
                </div>
            </a>
            <div class="md:hidden flex mb-10 mt-3 px-2 border-solid gap-3">
                <a href="{{ url_for('phostel.download', image_id=data.image.id) }}" download class="active:bg-sky-900 hover:bg-sky-600 flex item-center bg-biru-politik text-abu-indie p-2 rounded-md text-sm"><span class="material-symbols-outlined mr-2">download</span>Unduh</a>
            <button 
                type="button"
                hx-post="/like/{{ data.image.id }}"
                hx-swap="innerHTML"
                hx-target="#like-container-{{ data.image.id }}"
                hx-trigger="click"
                class="flex items-center text-abu-gelap"
            >
                <span id="like-container-{{ data.image.id }}" class="flex items-center">
                    {% if current_user.is_authenticated and data.liked %}
                      <span style="font-variation-settings: 'FILL' 1" class="cursor-pointer material-symbols-outlined mr-1 text-merah-merona">favorite</span>
                    {% else %}
                      <span class="cursor-pointer material-symbols-outlined mr-1">favorite</span>
                    {% endif %}
                    <span class="text-sm">{{ data.like_count }}</span>
                </span>
            </button>
            </div>
    </div>
{% endfor %}

templates/_load_related.html
{% for image in images %}
    <a href="{{ url_for('phostel.images', item_id=image.id) }}">
        <div class="md:rounded-md overflow-hidden mb-2">
            <img
                src="{{ url_for('static', filename='uploads/lqip/' + image.filename) }}"
                class="gallery bg-neutral-400 hover:brightness-70"
                data-src="{{ url_for('static', filename='uploads/thumbnails/' + image.filename) }}"
                loading="eager"
                style="aspect-ratio: {{ image.width }} / {{ image.height }};"
                alt="{{ image.title or image.filename }}"
            >
        </div>
    </a>
{% endfor %}

templates/_memuat.html
{% for image in images %}
    <div class="box max-w-full overflow-hidden">
            <div class="md:hidden pt-2 mb-2 flex px-2 items-center">
                <div>
                    {% if image.user.picture %}
                    <img src="{{ url_for('static', filename=image.user.picture) }}" alt="Profile Picture" class="mr-2 w-10 h-10 object-cover rounded-full active:brightness-70 hover:brightness-70">
                    {% else %}
                    <div class="mr-2 w-10 h-10 object-cover rounded-full bg-neutral-400 text-neutral-100 flex items-center justify-center select-none">
                        {{ image.user.username[0:1]|upper }}
                    </div>
                    {% endif %}
                </div>
                <div>
                    <p class="text-base text-hitam-pastel truncate">{{ image.user.username }}</p>
                </div>
            </div>
            <a href="{{ url_for('phostel.images', item_id=image.id) }}">
                <div class="md:rounded-md overflow-hidden">
                    <img
                        src="{{ url_for('static', filename='uploads/lqip/' + image.filename) }}"
                        class="gallery bg-neutral-400"
                        data-src="{{ url_for('static', filename='uploads/thumbnails/' + image.filename) }}"
                        loading="eager"
                        style="aspect-ratio: {{ image.width }} / {{ image.height }};"
                        alt="{{ image.title or image.filename }}"
                    >
                </div>
            </a>
            <div class="md:hidden flex mb-10 mt-3 px-2 border-solid gap-3">
                <a href="{{ url_for('phostel.download', image_id=image.id) }}" download class="active:bg-sky-900 hover:bg-sky-600 flex item-center bg-biru-politik text-abu-indie p-2 rounded-md text-sm"><span class="material-symbols-outlined mr-2">download</span>Unduh</a>
                <button data-dropdown-toggle="share" class="cursor-pointer flex items-center text-abu-gelap"><span class="material-symbols-outlined">share</span></button>
                <form method="POST" action="{{ url_for('phostel.like', image_id=image.id) }}" class="flex items-center text-abu-gelap">
                    <button type="submit" class="flex items-center">
                        {% if current_user.is_authenticated and liked %}
                        <span style="font-variation-settings: 'FILL' 1" class="material-symbols-outlined mr-1 cursor-pointer text-merah-merona">favorite</span> <!-- filled heart -->
                        {% else %}
                        <span class="material-symbols-outlined mr-1 cursor-pointer">favorite</span> <!-- empty heart -->
                        {% endif %}
                    </button>
                    <span>{{ like_count }}</span>
                </form>
                {% if current_user.is_authenticated and (image.user_id == current_user.id or current_user.admin) %}
                <button data-modal-target="hapus" class="cursor-pointer flex items-center text-abu-gelap" data-modal-toggle="hapus" type="button"><span class="material-symbols-outlined">delete</span></button>
                {% else %}
                {% endif %}
            </div>
    </div>
{% endfor %}

{% if has_next %}
<div hx-get="{{ url_for('phostel.load') }}?page={{ page + 1 }}" hx-trigger="revealed" hx-swap="afterend"
    class="load-trigger">
</div>
{% endif %}

templates/gambar.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ image.title or image.filename }}</title>
    <link rel="icon" type="image/x-icon" href="{{ url_for('static', filename='assets/img/favicon.png') }}">
    <script src="{{ url_for('static', filename='scripts/script.js') }}" defer></script>
    <script src="https://cdn.jsdelivr.net/npm/flowbite@3.1.2/dist/flowbite.min.js"></script>
    <script src="https://unpkg.com/boxicons@2.1.4/dist/boxicons.js" defer></script>
    <link rel="stylesheet" href="{{ url_for('static', filename='styles/styles.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='styles/output.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='photoswipe/photoswipe.css') }}">
    <script src="https://unpkg.com/htmx.org@2.0.4"></script>
    <link href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:FILL@0..1&icon_names=chevron_right,close,delete,download,favorite,link,local_police,logout,menu,search,share,upload" rel="stylesheet"/>    
    <meta name="theme-color" content="#DADADA">
</head>

<body class="text-sm bg-abu-indie">
    
    {% include 'navbar.html' %}

    <div id="share" class="z-10 m-5 hidden bg-abu-keputihan border-abu-putih border-solid border overflow-hidden rounded-lg shadow-lg w-64">
        <ul class="text-sm gap-3 divide-abu-putih divide-y " aria-labelledby="dropdownDefaultButton">
            <li class="grid p-2 gap-1">
                <button class="active:bg-neutral-300 hover:bg-neutral-300 flex item-center p-2 rounded-md" onclick="copyToClipboard('{{ url_for('phostel.images', item_id=image.id, _external=True) }}')"><box-icon type='logo' class="mr-2" name='instagram'></box-icon>Instagram</button>
                <button class="active:bg-neutral-300 hover:bg-neutral-300 flex item-center p-2 rounded-md" onclick="copyToClipboard('{{ url_for('phostel.images', item_id=image.id, _external=True) }}')"><box-icon type='logo' class="mr-2" name='twitter'></box-icon>Twitter</button>
                <button class="active:bg-neutral-300 hover:bg-neutral-300 flex item-center p-2 rounded-md" onclick="copyToClipboard('{{ url_for('phostel.images', item_id=image.id, _external=True) }}')"><box-icon type='logo' class="mr-2" name='pinterest'></box-icon>Pinterest</button>
                <button class="active:bg-neutral-300 hover:bg-neutral-300 flex item-center p-2 rounded-md" onclick="copyToClipboard('{{ url_for('phostel.images', item_id=image.id, _external=True) }}')"><box-icon type='logo' class="mr-2" name='whatsapp'></box-icon>Whatsapp</button>
                <button class="active:bg-neutral-300 hover:bg-neutral-300 flex item-center p-2 rounded-md" onclick="copyToClipboard('{{ url_for('phostel.images', item_id=image.id, _external=True) }}')"><span class="material-symbols-outlined mr-2">link</span>Salin Tautan</button>
            </li>
        </ul>
    </div>

    <main class="mt-20 mx-auto max-w-7xl text-sm m-5 md:p-3">
        <div class="item-baseline mx-auto max-w-7xl grid grid-cols-1 md:grid-cols-2 gap-2 xl:gap-10 mb-10">
            <a class="flex md:hidden pt-4 px-2" href="{{ url_for('phostel.user', user_id=image.user_id) }}">
                {% if user.picture %}
                <img src="{{ url_for('static', filename=user.picture) }}" alt="Profile Picture" class="mr-2 w-10 h-10 object-cover rounded-full active:brightness-70 hover:brightness-70">
                {% else %}
                <div class="mr-2 w-10 h-10 object-cover rounded-full bg-neutral-400 text-neutral-100 flex items-center justify-center select-none">
                    {{ user.username[0:1]|upper }}
                </div>
                {% endif %}                        
                <div>
                    <p class="text-sm"><span class="text-abu-gelap"></span>{{ image.user.username }}
                        {% if user.admin %}
                        <span class="text-biru-politik" title="Admin Phostel">[A]</span>
                        {% endif %}
                    </p>
                    <p class="text-sm text-abu-gelap mb-2">Diunggah {{ humanized_time }}</p>
                </div>
            </a>
            <div id="gallery" class="lg:max-h-[calc(100vh-7rem)] place-content-center bg-neutral-400 md:rounded-md overflow-hidden">
                <a class="cursor-zoom-in" href="{{ url_for('static', filename='uploads/' + image.filename) }}" data-pswp-width="{{ image.width }}" data-pswp-height="{{ image.height }}">
                    <img
                    src="{{ url_for('static', filename='uploads/lqip/' + image.filename) }}"
                    class="gallery"
                    data-src="{{ url_for('static', filename='uploads/thumbnails/' + image.filename) }}"
                    loading="eager"
                    style="aspect-ratio: {{ image.width }} / {{ image.height }};"
                    alt="{{ image.title or image.filename }}"
                    >
                </a>
            </div>
            <div class="flex flex-col gap-3 lg:overflow-y-auto lg:max-h-[calc(100vh-7rem)] no-scrollbar px-3">
                <div class="grid gap-3">
                    <p class="text-xl truncate">{{ image.title or image.filename }}</p>
                    <a class="md:flex hidden" href="{{ url_for('phostel.user', user_id=image.user_id) }}">
                        {% if user.picture %}
                        <img src="{{ url_for('static', filename=user.picture) }}" alt="Profile Picture" class="mr-2 w-10 h-10 object-cover rounded-full active:brightness-70 hover:brightness-70">
                        {% else %}
                        <div class="mr-2 w-10 h-10 object-cover rounded-full bg-neutral-400 text-neutral-100 flex items-center justify-center select-none">
                            {{ user.username[0:1]|upper }}
                        </div>
                        {% endif %}                        
                        <div>
                            <p class="text-sm"><span class="text-abu-gelap"></span>{{ image.user.username }}
                                {% if user.admin %}
                                <span class="text-biru-politik" title="Admin Phostel">[A]</span>
                                {% endif %}
                            </p>
                            <p class="text-sm text-abu-gelap mb-2">Diunggah {{ humanized_time }}</p>
                        </div>
                    </a>
                    <div class="flex flex-wrap gap-2">
                        {% if tags %}
                            {% for tag in tags.split(';') %}
                                {% if tag and tag.strip() %}
                                    <span class="border-abu-putih border p-1 px-2 rounded-md text-abu-gelap">{{ tag }}</span>
                                {% endif %}
                            {% endfor %}
                        {% endif %}
                    </div>
                </div>
                <div>
                    <div class="flex gap-5">
                        <a href="{{ url_for('phostel.download', image_id=image.id) }}" download class="active:bg-sky-900 hover:bg-sky-600 flex item-center bg-biru-politik text-abu-indie p-2 rounded-md"><span class="material-symbols-outlined mr-2">download</span>Unduh</a>
                        <button data-dropdown-toggle="share" class="cursor-pointer flex items-center text-abu-gelap"><span class="material-symbols-outlined">share</span></button>
                        <button 
                            type="button"
                            hx-post="/like/{{ image.id }}"
                            hx-swap="innerHTML"
                            hx-target="#like-container-{{ image.id }}"
                            hx-trigger="click"
                            class="flex items-center text-abu-gelap"
                        >
                            <span id="like-container-{{ image.id }}" class="flex items-center">
                                {% if current_user.is_authenticated and liked %}
                                <span style="font-variation-settings: 'FILL' 1" class="cursor-pointer material-symbols-outlined mr-1 text-merah-merona">favorite</span>
                                {% else %}
                                <span class="cursor-pointer material-symbols-outlined mr-1">favorite</span>
                                {% endif %}
                                <span class="text-sm">{{ like_count }}</span>
                            </span>
                        </button>
                        {% if current_user.is_authenticated and (image.user_id == current_user.id or current_user.admin) %}
                        <button data-modal-target="hapus" class="cursor-pointer flex items-center text-abu-gelap" data-modal-toggle="hapus" type="button"><span class="material-symbols-outlined">delete</span></button>
                        {% else %}
                        {% endif %}
                    </div>
                </div>
                {% if images %}
                <p class="text-xl mt-4 mb-2">Unggahan lain oleh {{ image.user.username }}</p>
                <div class="column-small" id="related">
                    {% include "_load_related.html" %}
                    {% if has_next %}
                    <div hx-get="{{ url_for('phostel.load_related') }}?page={{ page + 1 }}&user_id={{ image.user.id }}&exclude_id={{ image.id }}" hx-trigger="intersect once" hx-swap="beforeend" hx-target="#related" class="load-trigger">
                    </div>
                    {% endif %}
                </div>
                {% endif %}
            </div>
        </div>
    </main>

    <div id="hapus" tabindex="-1" class="bg-neutral-950/70 hidden overflow-y-auto overflow-x-hidden fixed top-0 right-0 left-0 z-50 justify-center items-center w-full md:inset-0 min-h-full">
        <div class="relative p-4 w-full max-w-md max-h-full">
            <div class="relative bg-abu-keputihan rounded-lg shadow-xl border-abu-gelap border-solid border">
                <button type="button" class="p-1 rounded-md hover:bg-neutral-200 active:bg-neutral-300 absolute top-3 end-3 flex justify-center items-center" data-modal-hide="hapus">
                    <span class="material-symbols-outlined cursor-pointer text-abu-gelap">close</span>
                    <span class="sr-only">Close modal</span>
                </button>
                <div class="p-4 md:p-5 grid justify-items-center">
                    <img class="h-20 mb-5" src="{{ url_for('static', filename='assets/img/warning.jpg') }}" alt="">
                    <h3 class="mb-5 font-normal">Apakah kamu yakin untuk menghapus gambar ini??</h3>
                    {% if current_user.admin %}
                    <span class="material-symbols-outlined text-biru-politik mb-2">local_police</span>
                    <h3 class="mb-5 font-normal text-biru-politik text-center">Kamu menggunakan hak admin untuk menghapus gambar ini!</h3>
                    {% endif %}
                    <div class="flex gap-2">
                        <form method="POST" action="{{ url_for('phostel.delete', image_id=image.id) }}" class="flex items-center text-abu-gelap">
                            <button type="submit" data-modal-hide="hapus" class="cursor-pointer bg-merah-merona hover:bg-red-400 active:bg-red-800 p-2 rounded-md flex items-center">
                                {% if current_user.is_authenticated and (image.user_id == current_user.id or current_user.admin) %}
                                <span class="material-symbols-outlined mr-1 text-abu-keputihan">delete</span><span class="text-abu-keputihan">Hapus</span>
                                {% else %}
                                {% endif %}
                            </button>
                        </form>
                        <button data-modal-hide="hapus" type="button" class="border-abu-gelap border-solid border text-abu-gelap hover:bg-neutral-200 active:bg-neutral-300 p-2 rounded-md flex items-center">Batalkan</button>
                    </div>
                </div>
            </div>
        </div>
    </div>

    {% include 'footer.html' %}      

</body>

<script>
    function copyToClipboard(text) {
        navigator.clipboard.writeText(text)
        .then(() => alert('Copied to clipboard!'))
        .catch(err => alert('Failed to copy: ' + err));
    }
</script>


<script>
    function init() {
        var imgDefer = document.getElementsByClassName('gallery');
        for (var i = 0; i < imgDefer.length; i++) {
            if (imgDefer[i].getAttribute('data-src') && !imgDefer[i].classList.contains('loaded')) {
                imgDefer[i].onload = function () {
                    this.classList.add('loaded');
                };
                imgDefer[i].setAttribute('src', imgDefer[i].getAttribute('data-src'));
            }
        }
    }
    window.onload = init;

    document.body.addEventListener('htmx:afterSwap', function(evt) {
        init();
    });
</script>

<script type="module">
    import PhotoSwipeLightbox from '/static/photoswipe/photoswipe-lightbox.esm.js';
    import PhotoSwipe from '/static/photoswipe/photoswipe.esm.js';

    const lightbox = new PhotoSwipeLightbox({
        gallery: '#gallery',
        children: 'a',
        pswpModule: () => PhotoSwipe
    });
    lightbox.init();
</script>

</html>